---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push
    tenant_id: tenant1

scrape_configs:
  - job_name: expable-api-express
    static_configs:
      - targets:
          - localhost
        labels:
          appname: food-log
          __path__: /logs/**.log
